bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
}

type_choices = {
  'buy':'BUY',
  'sell':'SELL',
  'rent':'RENT',
}

price_choices = {
  '500000':'$500,000',
  '600000':'$600,000',
  '700000':'$700,000',
  '800000':'$800,000',
  '900000':'$900,000',
  '1000000':'$1M+',
  '2000000':'$2M+',
  '5000000':'$5M+',
  '10000000':'$10M+',
  '20000000':'$20M+',
  '50000000':'$50M+',
  '100000000':'$100M+',
  '200000000':'$200M+',
  '500000000':'$500M+',
}

# state_choices = {
#         'NG-ABIA': 'Abia',
#         'NG-ADA': 'Adamawa',
#         'NG-IBOM': 'Akwa Ibom',
#         'NG-AKWA': 'Anambra',
#         'NG-BAU': 'Bauchi',
#         'NG-BYL': 'Bayelsa',
#         'NG-BEN': 'Benue',
#         'NG-BOR': 'Borno',
#         'NG-CAL': 'Cross River',
#         'NG-DEL': 'Delta',
#         'NG-EBO': 'Ebonyi',
#         'NG-EDO': 'Edo',
#         'NG-EKT': 'Ekiti',
#         'NG-ENU': 'Enugu',
#         'NG-FCT': 'Federal Capital Territory',
#         'NG-GOM': 'Gombe',
#         'NG-IMO': 'Imo',
#         'NG-JIG': 'Jigawa',
#         'NG-KAD': 'Kaduna',
#         'NG-KNO': 'Kano',
#         'NG-KST': 'Katsina',
#         'NG-KEB': 'Kebbi',
#         'NG-KOG': 'Kogi',
#         'NG-KWA': 'Kwara',
#         'NG-LOS': 'Lagos',
#         'NG-NAS': 'Nasarawa',
#         'NG-NIG': 'Niger',
#         'NG-OGN': 'Ogun ',
#         'NG-OND': 'Ondo',
#         'NG-OSN': 'Osun',
#         'NG-OYO': 'Oyo',
#         'NG-JOS': 'Plateau',
#         'NG-POR': 'Rivers',
#         'NG-SOK': 'Sokoto',
#         'NG-TAR': 'Taraba',
#         'NG-YOB': 'Yobe',
#         'NG-ZAM': 'Zamfara',
# }

state_choices = {
        'NG-ABIA': 'Alabama',
        'NG-ADA': 'Alaska',
        'NG-IBOM': 'Arizona',
        'NG-AKWA': 'California',
        'NG-BAU': 'Colorado',
        'NG-BYL': 'Florida',
        'NG-BEN': 'Georgia',
        'NG-BOR': 'Hawaii',
        'NG-CAL': 'Idaho',
        'NG-DEL': 'Illinois',
        'NG-EBO': 'Indiana',
        'NG-EDO': 'Iowa',
        'NG-EKT': 'Kansas',
        'NG-ENU': 'Maine',
        'NG-FCT': 'Maryland',
        'NG-GOM': 'Massachusetts',
        'NG-IMO': 'Michigan',
        'NG-JIG': 'Minnesota',
        'NG-KAD': 'Missouri',
        'NG-KNO': 'Nebraska',
        'NG-KST': 'Nevada',
        'NG-KEB': 'New Jersey',
        'NG-KOG': 'New Mexico',
        'NG-KWA': 'New York',
        'NG-LOS': 'North Carolina',
        'NG-NAS': 'Ohio',
        'NG-NIG': 'Pennsylvania',
        'NG-OGN': 'South Carolina',
        'NG-OND': 'South Dakota',
        'NG-OSN': 'Texas',
        'NG-OYO': 'Utah',
        'NG-JOS': 'Vermont',
        'NG-POR': 'Virginia',
        'NG-SOK': 'Washington',
        'NG-TAR': 'West Virginia',
        'NG-YOB': 'Wisconsin',
        'NG-ZAM': 'Wyoming',
}
